### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by mhinc14** [titel-media/react-apollo-multiple-clients#8]
I get a compilation error when trying to use this package and following the read.me example

`
./node_modules/@titelmedia/react-apollo-multiple-clients/src/withClient.jsx 11:4
Module parse failed: Unexpected token (11:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
|   return WrappedComponent => props => (
     <Consumer>
|       {context => (
|         <ApolloMultipleClientsConsumer>

`

I am using the react with typecript.

**Comment by dazlious** [comment]
Hi @mhinc14, you probably get the error because your babel/typescript compiler does not know about the plugins.

```
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.22.0",
    "babel-preset-stage-2": "^6.22.0",
```

You need all of these. I expect the `export-extensions` package is missing.

In general, if I can find the time, I can export the library as compiled ES5/6 code, so no one needs those plugins in the future.

Hope that helped you. I will close this for now, feel free to re-open this issue if you need further help.

**Comment by anthonyalviz** [comment]
@dazlious added the following babel packages above, but I still get the same error as OP.
